# GitHub Actions Workflow 이름
name: Random Picker (new) Frontend CI

# Workflows를 트리거할 이벤트 정의
on:
  pull_request:
    branches: [develop] # develop 브랜치로 PR이 열릴 때 실행됨
  push:
    branches: [develop] # develop 브랜치에 직접 push될 때도 실행됨

jobs:
  frontend-ci:
    name: Frontend Lint, Test, Build # Job 이름 (CI 결과 보기 좋게 설정)
    runs-on: ubuntu-latest # Ubuntu 최신 버전에서 실행됨

    steps:
      # 1. 레포지토리 코드를 체크아웃 (필수 단계)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설정 (현재는 20.17.0 사용 중)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
          cache: 'npm' # node_modules 캐시를 통해 npm install 속도 향상

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. Lint 실행
      - name: Run Lint
        run: npm run lint

      # 5. 테스트 실행
      # --if-present 옵션으로 test 스크립트가 없어도 에러 없이 넘어감
      # (--watch=false 옵션은 Jest, Vitest 등의 watch 모드 비활성화용)
      - name: Run Tests
        run: npm run test --if-present -- --watch=false

      # 6. 빌드 실행 (build가 성공하는지도 체크)
      - name: Run Build
        run: npm run build
